language: java
addons:
    sonarcloud:
        organization: steinarb-github
        token: $SONAR_TOKEN
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
    - mvn cobertura:cobertura coveralls:report

deploy:
    provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
